call plug#begin('~/.vim/plugged')
Plug 'vim-syntastic/syntastic'
Plug 'majutsushi/tagbar'
Plug 'maksimr/vim-jsbeautify'
Plug 'stephpy/vim-yaml'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'lifepillar/vim-solarized8'
call plug#end()
filetype on
autocmd Filetype python setlocal expandtab tabstop=4 shiftwidth=4
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
" syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:indentLine_char = '|'

nmap <F8> :TagbarToggle<CR>
nmap <C-n> :NERDTreeToggle<CR>

set tabstop=2
set shiftwidth=2
set expandtab

set background=dark
colorscheme solarized8_high
