#
# User configuration sourced by interactive shells
#

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

prompt 'pure'
# Created by newuser for 5.6.2
export EDITOR=vim

export VISUAL=vim

setopt RM_STAR_WAIT
# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
#
# else
#   export EDITOR='vim'
# fi


# Alias
alias dotdrop='/home/user/dotfiles/dotdrop.sh' --cfg='/home/user/dotfiles/config.yaml'
alias gs='git status'
alias ga='git add'
alias gm='git commit'
alias gp='git push'

grep='grep  --color=auto'

#autoload -Uz compinit
zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:*:*:kill:*:processes' list-colors "=(#b) #([0-9]#)*=36=31"


#https://github.com/timoxley/til/blob/master/shell/zsh-reporttime.md
export REPORTTIME=5



bindkey -e
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^B" backward-word
bindkey "^N" forward-word
bindkey "^?" backward-delete-char

#zstyle ':completion:*:*:kill:*' menu yes select
#zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
#zstyle ':completion:*:*:kill:*:processes' command 'ps xo pid,user:10,cmd | ack-grep -v "sshd:|-zsh$"'
