actions:
  pre:
    vimpluginst: test -e ~/.vim/autoload/plug.vim || (mkdir -p ~/.vim/autoload; curl
      -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: vim +PlugInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_plug.vim:
    dst: ~/.vim/autoload/plug.vim
    src: vim/autoload/plug.vim
  f_vimrc:
    actions:
    - vim-plug
    dst: ~/.vimrc
    src: vimrc
  f_zimrc:
    dst: ~/.zimrc
    src: zimrc
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  test:
    dotfiles:
    - f_bashrc
    - f_vimrc
    - f_plug.vim
    - f_zshrc
    - f_zimrc
